import { omit } from 'lodash'
import { DocumentDefinition } from 'mongoose'
import UserModel, { UserDocument } from '../models/user.model'

export async function createUser(
  input: DocumentDefinition<
    Omit<UserDocument, 'createdAt' | 'updatedAt' | 'comparePassword'>
  >
  // dont need to pass them here, will be generated by mongoose
) {
  try {
    // return await UserModel.create(input)
    const user = await UserModel.create(input)
    return omit(user.toJSON(), 'password')
  } catch (error: any) {
    throw new Error(error)
  }
}

export async function validatePassword({
  email,
  password,
}: {
  email: string
  password: string
}) {
  console.log('validate:', email) // validate: test@example.com
  const user = await UserModel.findOne({ email })

  if (!user) {
    console.log('validate: no user found')
    return false
  }

  const isValid = await user.comparePassword(password)
  console.log('isValid', isValid)

  if (!isValid) {
    console.log('validate: not valid pw')
    return false
  }

  return omit(user.toJSON(), 'password')
}
