import { DocumentDefinition } from 'mongoose'
import UserModel, { UserDocument } from '../models/user.model'

export async function createUser(
  input: DocumentDefinition<
    Omit<UserDocument, 'createdAt' | 'updatedAt' | 'comparePassword'>
  >
  // dont need to pass them here, will be generated by mongoose
) {
  try {
    return await UserModel.create(input)
  } catch (error: any) {
    throw new Error(error)
  }
}
